[project]
name = "easypyml"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Nils Malmberg" }
]
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.4.6",
]

[project.scripts]
easypyml = "easypyml:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
